Check minimum Kubewarden version.
kubewarden/policy-server pull request #445
Opened 2023-04-04 19:09 UTC by jvanz

## Description

Adds a function to check if the policy is running in a policy server with the minimum Kubewarden version required.

Fix #440

2023-04-06 19:28 UTC, jvanz commented on src/worker_pool.rs
> +        // it seems a bug in semver
Yes, this is my to do list. I want to report and send the fix soon

2023-04-11 11:24 UTC, flavio requested changes

2023-04-11 11:24 UTC, flavio commented on src/worker_pool.rs
> +        let kubewarden_version = Version::parse(env!("CARGO_PKG_VERSION")).ok().unwrap();
Generally speaking, you don't need to do `ok().unwrap()`, just use `unwrap`.

However, just use the lazy static constant you defined ahead. Also, give we have this constant now, I would change these tests to use [rstest](https://crates.io/crates/rstest) to DRY the code

2023-04-11 14:25 UTC, jvanz commented on src/worker_pool.rs
> +            build: minimum_kubewarden_version.build.clone(),
I kept this info on purpose. My original thought was using this to allow us enforce this kind of verification for releases candidates as well. But I'll remove it

2023-04-12 12:36 UTC, flavio approved these changes
I left one minor comment, once this is fixed we can merge it

2023-04-12 12:36 UTC, flavio commented on src/worker_pool.rs
> +            // Thus, we need to clone them
You have to remove this comment, it's outdated. I think you can slightly adapt the one on line 69, because it adapts to patch, pre and build

2023-04-12 15:29 UTC, flavio approved these changes
LGTM, merge it

2023-04-12 17:35 UTC, merged