fix: do not exit on policy error
kubewarden/policy-server pull request #712
Opened 2024-03-19 07:24 UTC by fabriziosestito

## Description

Fix #XXX

## Test

To test this pull request, you can run the following commands:

## Additional Information

### Tradeoff

### Potential improvement

2024-03-20 12:29 UTC, jvanz approved these changes

2024-03-20 12:29 UTC, jvanz commented on src/lib.rs
> +        // verify_policy_settings(&config.policies, &evaluation_environment).await?;
Remove this commented line. ;)

2024-03-21 10:52 UTC, viccuad approved these changes
LGTM modulo José's comment!

2024-03-22 13:48 UTC, flavio requested changes
LGTM, we can merge it as soon as the two changes requested are done (mine + the one from @jvanz)

2024-03-22 13:48 UTC, flavio commented on src/evaluation/precompiled_policy.rs
>  /// * value: the PrecompiledPolicy
Please update the inline doc, now this is a `Result<X>`, explain why we could be storing an `Err`

2024-03-22 14:23 UTC, flavio approved these changes

2024-03-22 14:33 UTC, merged