feat: add otlp endpoint config and cli flag
kubewarden/policy-server pull request #994
Opened 2024-12-05 12:15 UTC by fabriziosestito

## Description

This PR introduces a new `--otlp-endpoint` which changes metrics and traces gRPC OTLP  endpoint to the one specified by the user.

Part of #993 

## Test

Updates existing integration tests.

2024-12-05 12:58 UTC, jvanz requested changes
Unless we really want a CLI flag for this, I think we do not need it. The rust library does [check the environment variable for us](https://github.com/open-telemetry/opentelemetry-rust/blob/957659fac9217534e64d36f80bddc8360345fde5/opentelemetry-otlp/src/exporter/tonic/mod.rs#L191). 

I would add a CLI flag to define the certificate now instead. ;)

2024-12-05 13:44 UTC, fabriziosestito commented
@jvanz I think we should keep both the CLI flag and the config entry. It’s better to have consistent configurations, and exposing the certificate path only through the CLI could be confusing. Having the config struct map the otlp CLI values also makes integration tests easier.

2024-12-05 14:08 UTC, fabriziosestito commented on src/cli.rs
> +                .env("OTEL_EXPORTER_OTLP_ENDPOINT")
we could change this to `KUBEWARDEN_OTLP_ENDPOINT`if we decide to keep this cli flag

2024-12-05 20:41 UTC, jvanz commented
> @jvanz I think we should keep both the CLI flag and the config entry. It’s better to have consistent configurations, and exposing the certificate path only through the CLI could be confusing. Having the config struct map the otlp CLI values also makes integration tests easier.

Fair enough. I'm fine with that. I was mentioning that just to ensure that you're aware of this possibility. ;)

2024-12-05 20:42 UTC, jvanz approved these changes

2024-12-06 08:49 UTC, flavio approved these changes
LGTM

2024-12-06 13:02 UTC, merged